AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
  <% `git status --ignored --porcelain`.lines.grep(/^!! /).each do |path| %>
  - <%= path.sub(/^!! /, '').sub(/\/$/, '/**/*')  %>
  <% end %>

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'spec/**/*'
Metrics/BlockLength:
  Exclude:
    - '**/*.rake'
    - 'spec/**/*'
